config/routes.rb
Rails.application.routes.draw do

  root "theatres#root"

  resources :theatres do

    member do
      get 'spot'
    end

    collection do
      get 'search'
      get 'search_place'
      get 'display'
      get 'display_place'
      get 'root'
    end

  end

  resources :movies do

    member do
      get 'spot'
    end

    collection do
      get 'search'
      get 'display'
    end

  end

  resources :casts do

    collection do
      get 'search_hero'
      get 'display_hero'
      get 'search_heroine'
      get 'display_heroine'
    end

  end

  resources :shows, :crews

end

app/models/cast.rb
class Cast < ActiveRecord::Base
  belongs_to :movie

  def self.search_hero(query)
    where("hero like ?", "%#{query}%")
  end

  def self.search_heroine(query)
    where("heroine like ?", "%#{query}%")
  end

end

app/models/crew.rb
class Crew < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :theatres
  has_many :casts
  #has_and_belongs_to_many :shows
  has_many :shows

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  validates_uniqueness_of :theatre_id

  belongs_to :theatre
  belongs_to :movie

  #has_and_belongs_to_many :movies
end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
  has_many :shows

  has_and_belongs_to_many :movies

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

  def self.search_place(query)
    where("place like ?", "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  def new
    @cast = Cast.new
  end

  def create
    @cast = Cast.new(cast_params)
    @cast.save

    redirect_to cast_path(@cast)
  end

  def edit
    @cast = Cast.find(params[:id])
  end

  def update
    @cast = Cast.find(params[:id])
    @cast.update(cast_params)

    redirect_to cast_path(@cast)
  end

  def show
    @cast = Cast.find(params[:id])
  end

  def index
    @casts  = Cast.all
  end

  def display_hero
    @casts_hero  = Cast.search_hero(params[:search_hero])
  end

  def display_heroine
    @casts_heroine  = Cast.search_heroine(params[:search_heroine])

  end

  def destroy
    @cast = Cast.find(params[:id])
    @cast.delete

    redirect_to cast_path(@cast)
  end

  def cast_params
    params.require(:cast).permit(:movie_id, :hero, :heroine)
  end

end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  def new
    @crew = Crew.new
  end

  def create
    @crew = Crew.new(crew_params)
    @crew.save

    redirect_to new_crew_path
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
    @crews = Crew.all.order("category", "name")
  end

  def delete
  end

  def crew_params
    params.require(:crew).permit(:category, :name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def new
     @movie = Movie.new
  end

  def create
     @movie = Movie.new(movie_params)
     @movie.save

    redirect_to movie_path(@movie)

  end

  def search

  end

  def display
    @movies  = Movie.search(params[:search]).order("name")
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    redirect_to movie_path(@movie)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def index
    @movies = Movie.all.order('name')
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.delete

    redirect_to movies_path
  end

  def spot
    @movie = Movie.find(params[:id])
    @show_mor = Show.where(morning: params[:id])
    @show_mat = Show.where(matinee: params[:id])
    @show_fir = Show.where(first: params[:id])
    @show_sec = Show.where(second: params[:id])
  end


  def movie_params
    params.require(:movie).permit(:name, :language, :theatre_id)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def new
    @show = Show.new(theatre_id: params[:id])
  end

  def create
    @show = Show.create(show_params)

    redirect_to theatre_path(id: @show.theatre_id)
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    @show.update(show_params)

    redirect_to theatre_path(id: @show.theatre_id)
  end


  def destroy
    @show = Show.find(params[:id])
    @show.delete

    redirect_to theatres_path
  end

  def show_params
    params.require(:show).permit(:morning, :matinee, :first, :second, :theatre_id)
  end

end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def new
    @theatre = Theatre.new
  end

  def create
    @theatre = Theatre.new(theatre_params)
    @theatre.save

    redirect_to theatre_path(@theatre)
  end

  def edit
    @theatre = Theatre.find(params[:id])
  end

  def update
    @theatre = Theatre.find(params[:id])
    @theatre.update(theatre_params)

    redirect_to theatre_path(@theatre)
  end


  def show
    @theatre = Theatre.find(params[:id])
    #@show = Show.find_by_theatre_id(params[:id])
  end

  def index
    @theatres = Theatre.all.order('name')
  end

  def destroy
    @theatre = Theatre.find(params[:id])
    @theatre.delete

    redirect_to theatres_path
  end

  def search

  end

  def spot
     @theatre = Theatre.find(params[:id])
  end

  def display
    @theatres = Theatre.search(params[:search]).order("name")
  end

  def display_place
    @theatre_place  = Theatre.search_place(params[:search_place])
  end

  def theatre_params
    params.require(:theatre).permit(:name, :place)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/casts/display_hero.html.erb
<% if %>
    <% @casts_hero.blank? %>

    <h4> No Hero to display </h4>

<% else %>

<h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Heros and Movies <%#= @casts_hero.first.hero.upcase %> </h4>

<table class="table table-striped table-bordered">
  <tr>
    <th> Hero </td>
    <th> Movie  </td>
  </tr>
  <% @casts_hero.each do |cast| %>
      <tr>
         <td>  <%= cast.hero.upcase %> </td>
         <td>  <%= cast.movie.name.upcase %> </td>
      </tr>
  <% end %>

</table>

<% end %>

app/views/casts/display_heroine.html.erb
<% if %>
    <% @casts_heroine.blank? %>

    <h4> No Heroine to display </h4>

<% else %>

    <h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Heroines and Movies <%#= @casts_hero.first.hero.upcase %> </h4>

    <table class="table table-striped table-bordered">
      <tr>
        <th> Heroine </td>
        <th> Movie  </td>
      </tr>

      <% @casts_heroine.each do |cast| %>
          <tr>
            <td>  <%= cast.heroine.upcase %> </td>
            <td>  <%= cast.movie.name.upcase %> </td>
          </tr>
      <% end %>

    </table>

<% end %>

app/views/casts/edit.html.erb
<h6> Edit Cast for Movie </h6>

<%= form_for @cast do |cast| %>

    Movie : <%= cast.select :movie_id, Movie.all.collect {|t| [t.name, t.id] }, { include_blank: true} %>  <br>
    Hero : <%= cast.select(:hero, %w{ PawanKalyan Chiranjeevi RamCharanTej AlluArjun }, :include_blank => true) %>    <br> <br>
    Heroine : <%= cast.select(:heroine, %w{ Kajal Charmee Tamanna Rani Anushka NayanaTara}, :include_blank => true) %>    <br> <br>
    <%= cast.submit "Edit Cast" %>

<% end %>

app/views/casts/index.html.erb
<h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Movies and Cast </h4>

<table class="table table-striped table-bordered">

  <tr>
    <th> Movie </th>
    <th> Hero </th>
    <th> Heroine </th>
    <th> ACTION </th>
    <th> ACTION </th>
  </tr>

  <% @casts.each do |cast| %>
      <tr>
        <td>  <%= cast.movie.name.upcase %> </td>
        <td>  <%= cast.hero.upcase %> </td>
        <td>  <%= cast.heroine.upcase %> </td>
        <td> <%= link_to "EDIT",  edit_cast_path(cast) %>  </td>
        <td> <%= link_to "DELETE", cast_path(cast), method: :delete %>  </td>
      </tr>
  <% end %>


</table>

app/views/casts/new.html.erb
<h6> Create Cast for Movie </h6>

<%= form_for @cast do |cast| %>

      Movie : <%= cast.select :movie_id, Movie.all.collect {|t| [t.name, t.id] }, { include_blank: true} %>  <br>
       Hero : <%= cast.select :hero, Crew.where(category: "Hero").collect {|t| [t.name] }, { include_blank: true} %>   <br>
     Heroine : <%= cast.select :heroine, Crew.where(category: "Heroine").collect {|t| [t.name] }, { include_blank: true} %>   <br>
    <%= cast.submit "Create Cast" %>

<% end %>

app/views/casts/search_hero.html.erb
<%= form_tag(display_hero_casts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search_hero, params[:search], placeholder: "Search hero here" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/casts/search_heroine.html.erb
<%= form_tag(display_heroine_casts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search_heroine, params[:search], placeholder: "Search heroine here" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/casts/show.html.erb
<h6> Cast for the Movie </h6> <h4> <%= @cast.movie.name.upcase  %> </h4>
<hr />

Hero : <%= @cast.hero.upcase %>   <br />
Heroine: <%= @cast.heroine.upcase %> <br />

<%= link_to "Go Back to Main Page", root_theatres_path, :class => "btn btn-small btn-primary" %>
<%= link_to "Create another cast", new_cast_path, :class => "btn btn-small btn-success" %>

app/views/crews/edit.html.erb
<h1>Crews#edit</h1>
<p>Find me in app/views/crews/edit.html.erb</p>

app/views/crews/index.html.erb
<br>
<br>
<br>
<br>
<%= link_to "Create New Crew", new_crew_path, :class => 'btn btn-small btn-success' %>
<br>
<h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Crew </h4>

<table class="table table-hover table-condensed table-bordered">

  <tr>
    <th> Category </th>
    <th> Name </th>
    <th> ACTION </th>
    <th> ACTION </th>
  </tr>

  <% @crews.each do |crew| %>
      <tr>
        <td>  <%= crew.category.upcase %> </td>
        <td>  <%= crew.name.upcase %> </td>
        <td> <%= link_to "EDIT",  edit_crew_path(crew), :class => "btn btn-small btn-warning"  %>  </td>
        <td> <%= link_to "DELETE", crew_path(crew), method: :delete, :class => "btn btn-small btn-danger" %>  </td>
      </tr>
  <% end %>

</table>

app/views/crews/new.html.erb
<h6> Create New Crew </h6>

<%= form_for @crew do |crew| %>
    Category : <%= crew.select(:category, %w{ Hero Heroine }, :include_blank => true) %>    <br>
    Crew Name: <%= crew.text_field :name %>

    <%= crew.submit "Create Crew" %>
<% end %>

app/views/crews/show.html.erb
<h1>Crews#show</h1>
<p>Find me in app/views/crews/show.html.erb</p>

app/views/crews/update.html.erb
<h1>Crews#update</h1>
<p>Find me in app/views/crews/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Movieshows" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand"  href="#"> <i class="icon-home icon-large icon-white"></i> Movieshows</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_theatres_path  %></li>
              <li><%= link_to "Theatres", theatres_path  %></li>
              <li><%= link_to "Movies", movies_path  %></li>
              <li><%= link_to "Crew", crews_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"> Search Tools </li>
              <li><%= link_to "By Movies", search_movies_path  %></li>
              <li><%= link_to "By Theatres", search_theatres_path  %></li>
              <li><%= link_to "By Location", search_place_theatres_path  %></li>
              <li><%= link_to "By Hero", search_hero_casts_path  %></li>
              <li><%= link_to "By Heroine", search_heroine_casts_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/movies/display.html.erb
<h4> Displaying search results for Movies </h4>


<table class="table table-striped table-bordered">
  <tr>
    <th>Movie Name</th>



  </tr>

  <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.name.upcase, spot_movie_path(id: movie.id) %></td>


      </tr>
  <% end %>
</table>


<%= link_to "Go Back to Main Page", root_theatres_path, :class => "btn btn-small btn-primary" %>

app/views/movies/edit.html.erb
<%= form_for @movie  do |movie| %>

    Movie Name: <%= movie.text_field :name %> <br>
    Movie Language: <%= movie.text_field :language %> <br>
    <%= movie.submit "Update Movie" %>

<% end %>

app/views/movies/index.html.erb
<br>
<br>
<br>
<br>
<%= link_to "Create New Movie", new_movie_path, :class => 'btn btn-small btn-success' %>
<br>

<h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Movies </h4>

<table class="table table-hover table-condensed table-bordered">
  <tr>
    <th>Name</th>
    <th>Place</th>

    <th> ACTION </th>
    <th> ACTION </th>
    <th> Create Cast </th>

  </tr>

  <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.name.upcase, spot_movie_path(movie.id) %></td>
        <td><%= movie.language.capitalize %></td>

        <td> <%= link_to "EDIT", edit_movie_path(movie.id), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", movie_path(movie.id), :class => 'btn btn-mini btn-danger', method: :delete %> </td>
        <td> <%= link_to "Create Cast", new_cast_path, :class => 'btn btn-mini btn-success' %> </td>
      </tr>
  <% end %>
</table>

app/views/movies/new.html.erb
<%= form_for @movie  do |movie| %>

    Movie Name: <%= movie.text_field :name %> <br>
    Movie Language: <%= movie.text_field :language %> <br>
    <%= movie.submit "Create New Movie" %>

<% end %>

app/views/movies/search.html.erb
<%= form_tag(display_movies_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search movies here" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/movies/show.html.erb
<h4>Displaying details of Movie</h4>
<hr>

<h4> Movie Name: <%= @movie.name.upcase %> </h4> <br>
Movie Language: <%= @movie.language %> <br>
<small> <%= @movie.created_at %> |
 <%= @movie.updated_at %> </small>  <br>    <br>

<%= link_to "Go Back to Movies Page", movies_path, :class => "btn-info btn-small" %>

app/views/movies/spot.html.erb
<h4> Displaying Shows and theatres for <br> <br> "<%= @movie.name.upcase %>" Movie </h4>


<table class="table table-striped table-bordered">
  <tr>
    <th>MORNING (12:00) Show</th>
    <th>MATINEE (15:00) Show</th>
    <th>FIRST (18:00) Show</th>
    <th>SECOND (21:00) Show</th>
  </tr>

      <tr>
        <td>
          <% @show_mor.each do |show| %>
          <mark> <%= show.theatre.name.upcase %> </mark> <br>
          <% end %>
        </td>

        <td>
          <% @show_mat.each do |show| %>
          <mark> <%= show.theatre.name.upcase %> </mark> <br>
          <% end %>
        </td>

        <td>
          <% @show_fir.each do |show| %>
          <mark> <%= show.theatre.name.upcase %> </mark> <br>
          <% end %>
        </td>

        <td>
          <% @show_sec.each do |show| %>
          <mark> <%= show.theatre.name.upcase %> </mark> <br>
          <% end %>
        </td>

      </tr>

</table>

app/views/shows/edit.html.erb
<%= form_for @show do |show| %>

    Theatre : <%= show.select :theatre_id, Theatre.all.collect {|t| [t.name, t.id] }, { include_blank: true} %>  <br>
    Morning Show : <%= show.select :morning, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %>  <br>
    Matinee Show : <%= show.select :matinee, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true} %>  <br>
    First Show :   <%= show.select :first, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %> <br>
    Second Show :  <%= show.select :second, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %> <br>
    <br>

    <%= show.submit "Update Shows", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", theatres_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/shows/new.html.erb
<%= form_for @show do |show| %>

    Theatre : <%= show.select :theatre_id, Theatre.all.collect {|t| [t.name, t.id] }, { include_blank: true} %>  <br>
    Morning Show : <%= show.select :morning, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %>  <br>
    Matinee Show : <%= show.select :matinee, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true} %>  <br>
    First Show :   <%= show.select :first, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %> <br>
    Second Show :  <%= show.select :second, Movie.all.collect {|p|[p.name, p.id]}, { include_blank: true}  %> <br>
    <br>
    <%= show.submit "Create Shows", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", theatres_path, :class => 'btn btn-small btn-primary' %>

<% end %>

<%= params.inspect %>

app/views/theatres/display.html.erb
<h4> Displaying search results for Theatres </h4>

<table class="table table-striped table-bordered">
  <tr>
    <th>Theatre Name</th>

    </tr>

  <% @theatres.each do |theatre| %>
      <tr>
        <td><%= link_to theatre.name.upcase, spot_theatre_path(id: theatre.id) %></td>
      </tr>
  <% end %>
</table>
</body>

<%= link_to "Go Back to Main Page", root_theatres_path, :class => "btn btn-small btn-primary" %>

app/views/theatres/display_place.html.erb
<% if %>
    <% @theatre_place.blank? %>

    <h4> No Theatres to display </h4>

<% else %>

    <h6> Displaying Location and Theatre <%#= @casts_hero.first.hero.upcase %> </h6>

    <table class="table table-striped table-bordered">
      <tr>
        <th> Location </td>
        <th> Theatre Name </td>
      </tr>

      <% @theatre_place.each do |theatre| %>
          <tr>
            <td>  <%= theatre.place.upcase %> </td>
            <td>  <%= theatre.name.upcase %> </td>
          </tr>
      <% end %>

    </table>

<% end %>

app/views/theatres/edit.html.erb
<%= form_for @theatre do |theatre| %>

    Name :  <%= theatre.text_field :name  %> <br>
    Place  :  <%= theatre.text_field :place %>  <br>
    <br>
    <%= theatre.submit "Update Theatre", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", theatres_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/theatres/index.html.erb
<br>
<br>
<br>
<br>
<%= link_to "Create New Theatre", new_theatre_path, :class => 'btn btn-small btn-success' %>
<br>
<h4 style="color:chartreuse; text-align:center; background-color: orangered"> Displaying Theatres </h4>

<table class="table table-hover table-condensed table-bordered">
  <tr>
    <th>Name</th>
    <th>Place</th>

    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @theatres.each do |theatre| %>
      <tr>
        <td><%= link_to theatre.name.upcase, spot_theatre_path(theatre) %></td>
        <td><%= theatre.place.upcase %></td>

        <td> <%= link_to "EDIT", edit_theatre_path(theatre), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", theatre_path(theatre), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>

app/views/theatres/new.html.erb
<%= form_for @theatre do |theatre| %>

    Name :  <%= theatre.text_field :name  %> <br>
    Place  :  <%= theatre.text_field :place %>  <br>
   <br>
    <%= theatre.submit "Create New Theatre", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", theatres_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/theatres/root.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1> Welcome to MovieShows </h1>

app/views/theatres/search.html.erb
<%= form_tag(display_theatres_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search theatres here" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/theatres/search_place.html.erb
<%= form_tag(display_place_theatres_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search_place, params[:search_place], placeholder: "Search place of theatres here" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/theatres/show.html.erb
<h5> Displaying details of theatre</h5>
<hr>
<h6> Name:  <%= @theatre.name.upcase %> </h6> <br>
[ <small> <%= @theatre.place.upcase %> </small>] <br>
[<small> <%= @theatre.created_at %> | <%= @theatre.updated_at %> </small>]    <br> <br>

<%= link_to "Go Back to Theatre Page", theatres_path, :class => "btn btn-small btn-warning" %>
<%= link_to "Create Shows", new_show_path, :class => "btn btn-small btn-success" %>

app/views/theatres/spot.html.erb
<%#= link_to "Create New Theatre", new_theatre_path, :class => 'btn btn-small btn-success' %>

<h4> Displaying shows for "<%= @theatre.name.upcase %>" theatre </h4>


<table class="table table-striped table-bordered">
  <tr>
    <th>Morning Show</th>
    <th>Matinee Show</th>
    <th>First Show</th>
    <th>Second Show</th>
    <th>ACTION</th>


  </tr>

  <% @theatre.shows.each do |show| %>
  <tr>
     <td> <% a = show.morning %>  <%= Movie.find(a).name.upcase %> </td>
     <td> <% b = show.matinee %>  <%= Movie.find(b).name.upcase %> </td>
     <td> <% c = show.first %>  <%= Movie.find(c).name.upcase %> </td>
     <td> <% d = show.second %>  <%= Movie.find(d).name.upcase %> </td>
     <td> <%= link_to "EDIT", edit_show_path(show), :class => "btn btn-info btn-small" %></td>

  </tr>
  <% end %>
</table>